apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: devtron-cd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.6.1
    helm:
      values: |
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
        defaultSettings:
          backupTarget: s3://$(BACKUP_BUCKET)@$(BACKUP_REGION)/
          backupTargetCredentialSecret: longhorn-s3-secret
          storageOverProvisioningPercentage: 200
          storageMinimalAvailablePercentage: 15
          upgradeChecker: false
          defaultDataPath: /var/lib/longhorn
        ingress:
          enabled: true
          host: longhorn.internal.platform
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
